server:  # 服务器配置
  port: 8018  # 服务器端口号

spring:  # Spring 相关配置
  profiles:  # 激活的 Spring Profile
    active: k8s  # 激活 k8s Spring Profile
  application:  # 应用程序配置
    name: product-client  # 应用程序名称

ribbon:  # Ribbon 负载均衡配置
  eureka:  # Eureka 相关配置
    enable: true  # 启用 Ribbon 对 Eureka 的集成

feign:  # Feign 配置
  hystrix:  # Hystrix 配置
    enabled: true  # 在 Feign 中启用 Hystrix 熔断机制

eureka:  # Eureka 客户端配置
  instance:  # Eureka 实例配置
    prefer-ip-address: true  # 优先使用 IP 地址注册到 Eureka 服务器
  client:  # Eureka 客户端配置
    register-with-eureka: true  # 是否向 Eureka 注册自身
    fetch-registry: true  # 是否从 Eureka 服务器获取注册信息
    initial-instance-info-replication-interval-seconds: 10  # 初始实例信息复制间隔时间（以秒为单位）
    registry-fetch-interval-seconds: 5  # 从注册中心获取服务信息的时间间隔（以秒为单位）
    instance:  # Eureka 实例配置
      prefer-ip-address: true  # 优先使用 IP 地址作为实例标识
      lease-renewal-interval-in-seconds: 5  # 续约间隔时间（以秒为单位）
      lease-expiration-duration-in-seconds: 15  # 续约到期时间（以秒为单位）
